server:
  #端口号
  port: 8899
  #项目名，如果不设定，默认是 /
#  context-path: /spring-boot-mail

redis:
  task:
    host: 120.24.41.93
    port: 6379
    pass: rdd123456
    db: 2
    config:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000
